"use strict";

// Loading extensions into the pane's session.
//
// This is the impure half; `extension-policy.cjs` holds the decisions and is tested on its
// own. What lives here is only what needs a real Electron session: reading directories,
// calling loadExtension, and switching on the rulesets Electron forgot to.
//
// TWO MEASURED FACTS SHAPE THIS FILE, both from task-1-extensions.md:
//
// 1. **Electron 43 ignores `"enabled": true` on a manifest-declared static ruleset.** The
//    extension's own service worker reports `getEnabledRulesets() -> []` after loading. This
//    is the entire reason a previous measurement concluded that extension request blocking
//    does not work in Electron: the DNR engine was fine, the rules were never switched on.
//    uBO Lite calls `updateEnabledRulesets` during initialization, so keeping its worker alive
//    arms the same rules that Chrome would have armed from the manifest.
//
// 2. **Extensions that reach for a missing chrome.* namespace at module top level die
//    silently.** uBlock Origin Lite's background module does
//    `browser.permissions.onRemoved.addListener(...)` at top level and `chrome.permissions`
//    does not exist here, so the whole worker throws before uBOL reaches its own
//    `updateEnabledRulesets` call. That is why service-worker console output is surfaced into
//    the engine log: a dead worker is otherwise indistinguishable from a working one, and
//    `loadExtension` resolves cleanly either way.
//
// uBO Lite is adapted in a TWeb-owned RUNTIME COPY. Its downloaded source directory remains
// byte-for-byte untouched; a versioned copy gets a small wrapper service worker that supplies
// only the Electron APIs uBOL touches unconditionally before its feature detection can run.
// The adapter was not guessed: its exact resource-type blocking pattern was measured against
// uBOL's real default EasyList rules in an offscreen window.

const fs = require("node:fs");
const path = require("node:path");
const { classifyManifest, describeVerdict } = require("./extension-policy.cjs");

const UBOL_ADAPTER_VERSION = 1;

function safePathSegment(value) {
  const segment = String(value || "unknown").replace(/[^A-Za-z0-9._-]+/g, "_");
  return segment === "." || segment === ".." || segment === "" ? "unknown" : segment;
}

function isUblockOriginLite(manifest) {
  return manifest?.manifest_version === 3
    && manifest?.short_name === "uBO Lite"
    && manifest?.author === "Raymond Hill"
    && manifest?.background?.type === "module";
}

function ubolShimScript() {
  return `// Generated by TWeb's uBO Lite compatibility adapter.
const noopEvent = () => ({ addListener() {}, removeListener() {}, hasListener: () => false });
const permissions = () => ({
  onAdded: noopEvent(), onRemoved: noopEvent(),
  contains: (_p, cb) => cb ? (cb(true), undefined) : Promise.resolve(true),
  getAll: (cb) => { const r = { permissions: [], origins: ["<all_urls>"] };
    return cb ? (cb(r), undefined) : Promise.resolve(r); },
  request: (_p, cb) => cb ? (cb(true), undefined) : Promise.resolve(true),
  remove: (_p, cb) => cb ? (cb(false), undefined) : Promise.resolve(false),
});
const webNavigation = () => ({ onCommitted: noopEvent(), onCompleted: noopEvent(),
  onBeforeNavigate: noopEvent(), onHistoryStateUpdated: noopEvent(), onDOMContentLoaded: noopEvent() });
const action = () => ({ setIcon: async () => {}, setBadgeText: async () => {},
  setBadgeBackgroundColor: async () => {}, setTitle: async () => {}, setPopup: async () => {},
  getPopup: async () => "", enable: async () => {}, disable: async () => {}, onClicked: noopEvent() });
const contextMenus = () => ({ create: () => {}, remove: () => {}, update: () => {},
  removeAll: (cb) => cb && cb(), onClicked: noopEvent() });
const commands = () => ({ onCommand: noopEvent(),
  getAll: (cb) => cb ? (cb([]), undefined) : Promise.resolve([]) });
const notifications = () => ({ create: () => {}, clear: () => {}, onClicked: noopEvent(),
  onButtonClicked: noopEvent(), onClosed: noopEvent() });
const idle = () => ({ onStateChanged: noopEvent(), queryState: (_i, cb) => cb && cb("active"),
  setDetectionInterval: () => {} });
const browsingData = () => ({ remove: async () => {}, removeCache: async () => {} });
const privacy = () => ({ network: {}, websites: {}, services: {} });
for (const api of [self.chrome, self.browser].filter(Boolean)) {
  if (!api.permissions) api.permissions = permissions();
  if (!api.webNavigation) api.webNavigation = webNavigation();
  if (!api.action) api.action = action();
  if (!api.contextMenus) api.contextMenus = contextMenus();
  if (!api.commands) api.commands = commands();
  if (!api.notifications) api.notifications = notifications();
  if (!api.idle) api.idle = idle();
  if (!api.browsingData) api.browsingData = browsingData();
  if (!api.privacy) api.privacy = privacy();
}
`;
}

function prepareExtension(extensionDir, manifest, runtimeRoot, fsImpl = fs) {
  if (!isUblockOriginLite(manifest)) return { dir: extensionDir, manifest, adapted: false };
  const target = path.join(
    runtimeRoot,
    `ubol-${safePathSegment(manifest.version)}-adapter-${UBOL_ADAPTER_VERSION}`,
  );
  const targetManifest = path.join(target, "manifest.json");
  if (!fsImpl.existsSync(targetManifest)) {
    fsImpl.mkdirSync(runtimeRoot, { recursive: true });
    const staging = `${target}.tmp-${process.pid}`;
    fsImpl.rmSync(staging, { recursive: true, force: true });
    fsImpl.cpSync(extensionDir, staging, { recursive: true });
    fsImpl.writeFileSync(path.join(staging, "tweb-compat.js"), ubolShimScript(), { mode: 0o600 });
    fsImpl.writeFileSync(
      path.join(staging, "tweb-background.js"),
      'import "/tweb-compat.js";\nimport "/js/background.js";\n',
      { mode: 0o600 },
    );
    const adaptedManifest = {
      ...manifest,
      background: { service_worker: "/tweb-background.js", type: "module" },
    };
    fsImpl.writeFileSync(
      path.join(staging, "manifest.json"),
      `${JSON.stringify(adaptedManifest, null, 2)}\n`,
      { mode: 0o600 },
    );
    try {
      fsImpl.renameSync(staging, target);
    } catch (error) {
      fsImpl.rmSync(staging, { recursive: true, force: true });
      if (!fsImpl.existsSync(targetManifest)) throw error;
    }
  }
  return { dir: target, manifest: readManifest(target, fsImpl), adapted: true };
}

// TWEB_EXTENSIONS_DIR overrides it, which is how the real-pane measurement drove a scratch
// copy without touching whatever the user has installed.
function extensionsDir(env = process.env, userDataDir) {
  const override = env.TWEB_EXTENSIONS_DIR;
  if (typeof override === "string" && override !== "") return override;
  return path.join(userDataDir, "extensions");
}

/**
 * The immediate subdirectories of `dir` that contain a manifest.json, sorted.
 *
 * Sorted because load order decides which extension's rule wins a DNR priority tie, and an
 * order that depends on the filesystem's whim makes a blocking result unreproducible.
 */
function extensionDirs(dir, fsImpl = fs) {
  let entries;
  try {
    entries = fsImpl.readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }
  return entries
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
    .map((entry) => path.join(dir, entry.name))
    .filter((candidate) => {
      try {
        return fsImpl.statSync(path.join(candidate, "manifest.json")).isFile();
      } catch {
        return false;
      }
    })
    .sort();
}

function readManifest(dir, fsImpl = fs) {
  try {
    return JSON.parse(fsImpl.readFileSync(path.join(dir, "manifest.json"), "utf8"));
  } catch (error) {
    return { __readError: String(error.message || error) };
  }
}

/**
 * The ruleset ids a manifest declares as enabled.
 *
 * Chrome would have honoured this itself. Electron does not, so the host re-states it.
 */
function declaredRulesetIds(manifest) {
  const resources = manifest?.declarative_net_request?.rule_resources;
  if (!Array.isArray(resources)) return [];
  return resources
    .filter((resource) => resource && resource.enabled !== false && typeof resource.id === "string")
    .map((resource) => resource.id);
}

async function startBackgroundWorker(
  ses,
  scope,
  { attempts = 30, wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms)) } = {},
) {
  let lastError = null;
  for (let attempt = 0; attempt < attempts; attempt += 1) {
    try {
      await ses.serviceWorkers.startWorkerForScope(scope);
      return { started: true, error: null };
    } catch (error) {
      lastError = String(error.message || error);
      if (attempt + 1 < attempts) await wait(100);
    }
  }
  return { started: false, error: lastError || "Failed to start service worker." };
}

/**
 * Load every supported extension found in `dir` into `ses`.
 *
 * Returns one record per candidate directory — refusals included, because a refusal is a
 * result the user needs to see, not an absence.
 *
 * Must be awaited BEFORE the first navigation in the session: a rule that is enabled after a
 * page has started loading does not retroactively block that page's requests.
 */
async function loadExtensions(
  ses,
  dir,
  { log = () => {}, fsImpl = fs, runtimeRoot = null, workerOptions = undefined } = {},
) {
  const results = [];
  const staging = runtimeRoot || path.join(dir, ".tweb-runtime");
  for (const sourceDir of extensionDirs(dir, fsImpl)) {
    const sourceManifest = readManifest(sourceDir, fsImpl);
    const name = path.basename(sourceDir);
    if (sourceManifest.__readError) {
      results.push({ dir: sourceDir, loaded: false, verdict: null, error: sourceManifest.__readError });
      log(`extension ${name}: refused — manifest.json unreadable (${sourceManifest.__readError})`);
      continue;
    }

    let extensionDir = sourceDir;
    let manifest = sourceManifest;
    let adapted = false;
    try {
      const prepared = prepareExtension(sourceDir, sourceManifest, staging, fsImpl);
      extensionDir = prepared.dir;
      manifest = prepared.manifest;
      adapted = prepared.adapted;
    } catch (error) {
      const message = String(error.message || error);
      results.push({ dir: sourceDir, loaded: false, verdict: null, error: message });
      log(`extension ${name}: refused — compatibility copy failed (${message})`);
      continue;
    }

    const verdict = classifyManifest(manifest);
    if (!verdict.supported) {
      results.push({ dir: extensionDir, loaded: false, verdict, error: null });
      log(`extension ${describeVerdict(verdict)}`);
      continue;
    }

    let loaded;
    try {
      loaded = await ses.extensions.loadExtension(extensionDir, { allowFileAccess: true });
    } catch (error) {
      const message = String(error.message || error);
      results.push({ dir: extensionDir, loaded: false, verdict, error: message });
      log(`extension ${verdict.name || name}: load failed — ${message}`);
      continue;
    }

    const rulesetIds = declaredRulesetIds(manifest);
    let serviceWorkerStarted = false;
    let workerError = null;
    if (manifest.background?.service_worker) {
      const status = await startBackgroundWorker(
        ses,
        `chrome-extension://${loaded.id}/`,
        workerOptions,
      );
      serviceWorkerStarted = status.started;
      workerError = status.error;
    }
    results.push({
      dir: extensionDir,
      loaded: true,
      verdict,
      error: null,
      id: loaded.id,
      rulesetIds,
      serviceWorkerStarted,
      workerError,
      adapted,
    });
    log(`extension ${describeVerdict(verdict)}${adapted ? " (TWeb compatibility adapter)" : ""}`);
    if (workerError) {
      // This has two measured meanings that Electron does not distinguish: another process
      // owns the scope (and its DNR rules DO apply here), or the worker truly could not start.
      // Keep the extension loaded — removing it disarms the working first case — and make the
      // ambiguity visible instead of claiming a successful worker.
      log(`extension ${verdict.name || name}: background worker not running in this engine`
        + ` (${workerError}); restart all TWeb panes together if blocking is not active`);
    }
    if (rulesetIds.length > 0) {
      log(`extension ${verdict.name || name}: declares ${rulesetIds.length} static ruleset(s)`);
    }
  }
  return results;
}

/**
 * Wire an extension's service-worker console output into the engine log.
 *
 * The measured reason: an extension whose background worker throws on a missing chrome.* API
 * is indistinguishable, from the outside, from one that is working — `loadExtension` resolves,
 * `getAllExtensions` lists it, and nothing blocks. The worker's own TypeError is the only
 * evidence, and it is otherwise thrown away.
 */
function watchServiceWorkers(ses, { log = () => {} } = {}) {
  ses.serviceWorkers.on("console-message", (_event, details) => {
    const level = String(details.level || "");
    // info/verbose from a healthy blocker is chatty enough to evict everything else from the
    // engine log's ring buffer. Errors and warnings are the ones that mean something failed.
    if (level !== "error" && level !== "warning") return;
    const source = String(details.sourceUrl || "").replace(/^chrome-extension:\/\//, "");
    log(`extension worker ${level}: ${source}:${details.lineNumber || 0} ${details.message}`);
  });
}

module.exports = {
  UBOL_ADAPTER_VERSION,
  declaredRulesetIds,
  extensionDirs,
  extensionsDir,
  isUblockOriginLite,
  loadExtensions,
  prepareExtension,
  readManifest,
  safePathSegment,
  startBackgroundWorker,
  ubolShimScript,
  watchServiceWorkers,
};
